kind: Pod
apiVersion: v1
metadata:
 name: multicontainer
 namespace: default
 labels: # any key and value pair
  author: rafi
  type: webserver
  env: dev
spec:
 containers:
  - name: c1
    image: nginx
  - name: c2
    image: tomcat
