apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  namespace: default
  labels:
    author: rafi
    type: webserver
    env: dev
spec:
  containers:
    - name: c1
      image: nginx
    - name: c2
      image: tomcat

